package com.kongkongmao.dots.gui;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.nio.ByteBuffer;
import javax.imageio.ImageIO;
import org.lwjgl.BufferUtils;

import static org.lwjgl.opengl.GL11.*;
import static org.lwjgl.opengl.GL13.*;

/**
 * Class: Texture <br>
 * Package: com.kongkongmao.dots.gui <br>
 * Description: The working frame of the 2D textures in the form of files.
 */
public class Texture {

	/**
	 * ID of the texture that is automatically generated by OpenGL.
	 */
	private int id;

	private int width, height;

	public Texture(String file) {
		BufferedImage bi;
		try {
			bi = ImageIO.read(new File(file));
			width = bi.getWidth();
			height = bi.getHeight();
			int[] pixels_r = new int[width * height];
			pixels_r = bi.getRGB(0, 0, width, height, null, 0, width);
			ByteBuffer pixels = BufferUtils.createByteBuffer(width * height * 4);

			for (int i = 0; i < width; i++)
				for (int j = 0; j < height; j++) {
					int pixel = pixels_r[i * width + j];
					pixels.put((byte) ((pixel >> 020) & 0xff)); // R
					pixels.put((byte) ((pixel >> 010) & 0xff)); // G
					pixels.put((byte) (pixel & 0xff)); // B
					pixels.put((byte) ((pixel >> 030) & 0xff)); // A
				}

			pixels.flip();
			id = glGenTextures();

			glBindTexture(GL_TEXTURE_2D, id);

			glTexParameterf(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_NEAREST);
			glTexParameterf(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_NEAREST);

			glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, width, height, 0, GL_RGBA, GL_UNSIGNED_BYTE, pixels);

		} catch (IOException e) {
			e.printStackTrace();
		}
	}

	/**
	 * Bind the texture.
	 */
	public void bind(int sampler) {
		if (sampler >= 0 && sampler <= 31)
			glActiveTexture(GL_TEXTURE0 + sampler);
		glBindTexture(GL_TEXTURE_2D, id);
	}

}
